# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0002_auto_20170301_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='archivo', max_length=255),
            preserve_default=False,
        ),
    ]
