# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0006_auto_20170302_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_to_text',
            field=models.TextField(blank=True),
        ),
    ]
