# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0012_auto_20170303_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='asignatura',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de la asignatura'),
        ),
        migrations.AlterField(
            model_name='document',
            name='bibliografias',
            field=models.TextField(blank=True, verbose_name='Referencias Bibliográficas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='contenidos',
            field=models.TextField(blank=True, verbose_name='Contenidos Sinópticos'),
        ),
        migrations.AlterField(
            model_name='document',
            name='creditos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Créditos'),
        ),
        migrations.AlterField(
            model_name='document',
            name='evaluacion',
            field=models.TextField(blank=True, verbose_name='Estrategias de Evaluación'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Entrada en Vigencia'),
        ),
        migrations.AlterField(
            model_name='document',
            name='horas_lab',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='document',
            name='horas_practica',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de Práctica'),
        ),
        migrations.AlterField(
            model_name='document',
            name='horas_teoria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de Teoría'),
        ),
        migrations.AlterField(
            model_name='document',
            name='metodologias',
            field=models.TextField(blank=True, verbose_name='Estrategias Metodológicas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='objetivos',
            field=models.TextField(blank=True, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='document',
            name='requisitos',
            field=models.TextField(blank=True, verbose_name='Requisitos'),
        ),
    ]
