# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0013_auto_20170303_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='trimestre',
            field=models.CharField(choices=[('AB', 'Abril - Julio'), ('EM', 'Enero - Marzo'), ('SD', 'Septiembre - Diciembre')], default='EM', max_length=2),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2017), django.core.validators.MinValueValidator(1969)], verbose_name='Año'),
        ),
    ]
