# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0014_auto_20170303_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='scanned',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.IntegerField(blank=True, default=2017, null=True, validators=[django.core.validators.MaxValueValidator(2017), django.core.validators.MinValueValidator(1969)], verbose_name='Año'),
        ),
    ]
