# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0015_auto_20170303_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents', verbose_name='Documento A Subir'),
        ),
        migrations.AlterField(
            model_name='document',
            name='scanned',
            field=models.BooleanField(verbose_name='Utilizar Reconocimiento de Caracteres'),
        ),
    ]
