# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0016_auto_20170303_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_teoria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de Teoría')),
                ('h_prac', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de Práctica')),
                ('h_lab', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de Laboratorio')),
                ('fecha_vigtrim', models.CharField(choices=[('AB', 'Abril - Julio'), ('EM', 'Enero - Marzo'), ('SD', 'Septiembre - Diciembre')], default='EM', max_length=2)),
                ('fecha_vigano', models.IntegerField(blank=True, default=2017, null=True, validators=[django.core.validators.MaxValueValidator(2017), django.core.validators.MinValueValidator(1969)], verbose_name='Año')),
                ('obj_g', models.TextField(blank=True, verbose_name='Referencias Bibliográficas')),
                ('obj_e', models.TextField(blank=True, verbose_name='Referencias Bibliográficas')),
                ('contenidos', models.TextField(blank=True, verbose_name='Referencias Bibliográficas')),
                ('estrategias', models.TextField(blank=True, verbose_name='Estrategias Metodológicas')),
                ('estrat_eval', models.TextField(blank=True, verbose_name='Estrategias de Evaluación')),
                ('fuentes', models.TextField(blank=True, verbose_name='Fuentes de Información')),
                ('cronograma', models.TextField(blank=True, verbose_name='Cronograma')),
                ('sinoptico', models.TextField(blank=True, verbose_name='Contenidos Sińópticos')),
            ],
        ),
    ]
