# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0016_auto_20170303_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='justificacion',
            field=models.TextField(blank=True, verbose_name='Justifición'),
        ),
    ]
