# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0017_document_justificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('value', models.TextField(blank=True, verbose_name='Texto')),
                ('document', models.ManyToManyField(to='historia1.Document')),
            ],
        ),
    ]
