# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0017_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código de la materia'),
        ),
        migrations.AddField(
            model_name='programa',
            name='materia',
            field=models.CharField(blank=True, max_length=255, verbose_name='Denominación'),
        ),
        migrations.AlterField(
            model_name='document',
            name='asignatura',
            field=models.CharField(blank=True, max_length=255, verbose_name='Denominación'),
        ),
        migrations.AlterField(
            model_name='document',
            name='bibliografias',
            field=models.TextField(blank=True, verbose_name='Fuentes de Información Recomendadas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='creditos',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)], verbose_name='Créditos'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='contenidos',
            field=models.TextField(blank=True, verbose_name='Contenidos'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fuentes',
            field=models.TextField(blank=True, verbose_name='Fuentes de Información Recomendadas'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='obj_e',
            field=models.TextField(blank=True, verbose_name='Objetivos Específicos'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='obj_g',
            field=models.TextField(blank=True, verbose_name='Objetivos Generales'),
        ),
    ]
