# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0018_auto_20170313_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='document',
            name='creditos',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)], verbose_name='Unidades Créditos'),
        ),
        migrations.AlterField(
            model_name='document',
            name='trimestre',
            field=models.CharField(choices=[('AB', 'Abril - Julio'), ('EM', 'Enero - Marzo'), ('SD', 'Septiembre - Diciembre'), ('NN', 'Ninguno')], default='NN', max_length=2),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2017), django.core.validators.MinValueValidator(1969)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_vigano',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2017), django.core.validators.MinValueValidator(1969)], verbose_name='Año'),
        ),
    ]
