# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0018_camposextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='justificacion',
            field=models.TextField(blank=True, verbose_name='Justificación'),
        ),
    ]
