# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0019_auto_20170313_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='fecha_vigtrim',
            field=models.CharField(choices=[('AB', 'Abril - Julio'), ('EM', 'Enero - Marzo'), ('SD', 'Septiembre - Diciembre'), ('NN', 'Ninguno')], default='NN', max_length=2),
        ),
    ]
