# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0019_auto_20170314_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camposextra',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='hola',
            field=models.ManyToManyField(to='historia1.CamposExtra'),
        ),
    ]
