# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0020_auto_20170315_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='hola',
            new_name='extra',
        ),
    ]
