# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0020_auto_20170316_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='apellido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='autores',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='edicion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='editorial',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
