# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0021_auto_20170315_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='extra',
        ),
        migrations.AddField(
            model_name='camposextra',
            name='document',
            field=models.ManyToManyField(to='historia1.Document'),
        ),
    ]
