# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0021_auto_20170313_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.CharField(blank=True, max_length=128, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='document',
            name='nombre',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='document',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
    ]
