# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0022_auto_20170314_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='guardar',
            field=models.CharField(choices=[('SA', 'PASA'), ('TR', 'Transcripción')], default='TR', max_length=2),
        ),
    ]
