# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0023_document_guardar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='guardar',
            field=models.CharField(choices=[('PASA', 'PASA'), ('TRAN', 'Transcripción')], default='TRAN', max_length=4, verbose_name='Guardar como:'),
        ),
    ]
