# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0024_auto_20170314_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='horas_lab',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Horas de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='document',
            name='horas_practica',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Horas de Práctica'),
        ),
        migrations.AlterField(
            model_name='document',
            name='horas_teoria',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Horas de Teoría'),
        ),
    ]
