# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0025_auto_20170315_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='horas_lab',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='document',
            name='horas_practica',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas de Práctica'),
        ),
        migrations.AlterField(
            model_name='document',
            name='horas_teoria',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas de Teoría'),
        ),
    ]
