# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 01:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0026_auto_20170315_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='creditos',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)], verbose_name='Unidades Créditos'),
        ),
    ]
