# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0031_auto_20170315_2152'),
        ('historia1', '0023_auto_20170315_0331'),
    ]

    operations = [
    ]
