# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0032_merge_20170316_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='horas_lab',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Horas de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='document',
            name='horas_practica',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Horas de Práctica'),
        ),
        migrations.AlterField(
            model_name='document',
            name='horas_teoria',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Horas de Teoría'),
        ),
        migrations.AlterField(
            model_name='document',
            name='justificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Justificación'),
        ),
    ]
