# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0033_auto_20170316_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camposextra',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='camposextra',
            name='value',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
    ]
