# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia1', '0034_auto_20170330_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camposextra',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='camposextra',
            name='value',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
